spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/soa2
#    username: postgres
#    password: admin
    username: s311685
    password:
    url: jdbc:postgresql://localhost:5432/studs
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 23580
  ssl:
    enabled: true
    key-store: classpath:static/certificates/keystore.p12
    key-store-password: paspas
    key-store-type: PKCS12
    key-alias: mycert
