server:
  port: 8083
  ssl:
    enabled: true
    key-store: classpath:static/certificates/keystore.p12
    key-store-password: paspas
    key-store-type: PKCS12
    key-alias: mycert

spring:
  main:
    allow-bean-definition-overriding: true

first-service:
  url: ${FIRST_SERVICE_URL:https://localhost}
  port: ${FIRST_SERVICE_PORT:8443}


